/* VANTA SYSTEM · local-first command runtime. No secrets, no remote calls. */
(() => {
  'use strict';
  const $ = (s) => document.querySelector(s);
  const profiles = { Fran: 'OPERADOR PRINCIPAL', 'Angélica': 'PERFIL PERSONAL' };
  let profile = localStorage.getItem('vanta.profile') || '';
  let data;
  let listening = false;
  const key = (name) => `vanta.${profile}.${name}`;
  const load = () => { try { data = JSON.parse(localStorage.getItem(key('data')) || '{}'); } catch { data = {}; } data.memory ||= []; data.history ||= []; data.session ||= 0; data.settings ||= { personality:'directo', model:'local-fallback', rate:.95, pitch:1 }; };
  const save = () => localStorage.setItem(key('data'), JSON.stringify(data));
  const setStatus = (main, detail = 'Canal local seguro · sin claves expuestas') => { $('#status').textContent = main; $('#status-detail').textContent = detail; };
  const say = (text, speak = true) => { $('#vanta-message').textContent = text; if (!speak || !('speechSynthesis' in window)) return; speechSynthesis.cancel(); const u = new SpeechSynthesisUtterance(text); u.lang='es-AR'; u.rate=Number(data.settings.rate); u.pitch=Number(data.settings.pitch); const voice = speechSynthesis.getVoices().find(v => v.lang.toLowerCase().startsWith('es')); if (voice) u.voice=voice; $('#waveform').classList.add('active'); $('#voice-status').textContent='SPEAKING'; u.onend=()=>{$('#waveform').classList.remove('active');$('#voice-status').textContent='VOICE READY';}; speechSynthesis.speak(u); };
  const render = () => { $('#active-profile').textContent=profile.toUpperCase(); $('#profile-role').textContent=profiles[profile]; $('#profile-button').textContent=profile==='Angélica'?'AN':'FR'; $('#memory-count').textContent=data.memory.length; $('#session-count').textContent=data.session; $('#model-label').textContent=data.settings.model.replace(/^local-/,'').toUpperCase(); $('#personality').value=data.settings.personality; $('#model').value=data.settings.model; $('#rate').value=data.settings.rate; $('#rate-output').textContent=Number(data.settings.rate).toFixed(2); $('#pitch').value=data.settings.pitch; $('#pitch-output').textContent=Number(data.settings.pitch).toFixed(2); const list=$('#history-list'); list.innerHTML=data.history.length ? data.history.slice().reverse().map((x)=>`<li>${escapeHtml(x.text)} <small>${x.time}</small></li>`).join('') : '<li class="empty">No hay comandos todavía.</li>'; };
  const escapeHtml = (s) => { const d=document.createElement('div'); d.textContent=s; return d.innerHTML; };
  const localResponse = (raw) => { const text=raw.trim(), low=text.toLowerCase(); if (/\b(ayuda|help|comandos)\b/.test(low)) return 'Puedo trabajar offline. Probá: informe del sistema, qué recordás, recordá que…, borrar memoria, modo directo, modo amigable, modo sarcástico o descansar.'; if (low.includes('informe')||low.includes('estado')) return `Sistema operativo, ${profile}. Sesión ${data.session}, ${data.memory.length} recuerdos locales y modelo ${data.settings.model}. Conexión externa desactivada.`; if (low.includes('qué record')||low.includes('memoria')) return data.memory.length ? `Tengo ${data.memory.length} recuerdo${data.memory.length===1?'':'s'} local${data.memory.length===1?'':'es'}: ${data.memory.join('; ')}.` : 'La memoria está limpia. Una pizarra impecable: sospechosamente eficiente.'; const remember=low.match(/(?:recordá|recuerda|acordate de|memoriza)\s+(?:que\s+)?(.+)/i); if (remember) { const item=remember[1].trim(); if (!data.memory.includes(item)) data.memory.push(item); data.memory=data.memory.slice(-30); save(); render(); return `Guardado en la memoria privada de ${profile}: “${item}”.`; } if (low.includes('borrar memoria')) { data.memory=[]; save(); render(); return 'Memoria local borrada. Cero fantasmas, cero drama.'; } const modes=['directo','amigable','formal','sarcástico','sarcastico','misterioso']; const mode=modes.find(m=>low.includes(m)); if (mode) { data.settings.personality=mode==='sarcástico'?'sarcastico':mode; save(); render(); return `Personalidad ${mode} activada. Mucho mejor que una reunión, señor.`; } if (/\b(descans|dorm|cancel|deten)/.test(low)) { stop(); return 'Modo reposo activado.'; } return `Recibido: “${text}”. Estoy en modo local; para conectar un modelo externo, configurá un proxy de desarrollo sin exponer claves en el repositorio.`; };
  const submit = (value) => { const text=value.trim(); if(!text) return; $('#command').value=''; $('#user-message').textContent=text; $('#last-time').textContent=new Date().toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'}); data.session++; data.history.push({text,time:new Date().toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})}); data.history=data.history.slice(-40); save(); render(); setStatus('PROCESANDO…','Motor local en ejecución'); window.setTimeout(()=>{say(localResponse(text)); setStatus('SISTEMA EN REPOSO');},120); };
  const stop = () => { if ('speechSynthesis' in window) speechSynthesis.cancel(); listening=false; $('#waveform').classList.remove('active'); $('#voice-status').textContent='VOICE READY'; setStatus('RESPUESTA DETENIDA'); };
  const initApp = () => { load(); $('#onboarding').hidden=true; $('#app').hidden=false; render(); setStatus('SISTEMA EN REPOSO'); };
  document.querySelectorAll('[data-profile]').forEach(b=>b.addEventListener('click',()=>{profile=b.dataset.profile;localStorage.setItem('vanta.profile',profile);initApp();}));
  if (profile) initApp();
  $('#send').addEventListener('click',()=>submit($('#command').value)); $('#command').addEventListener('keydown',e=>{if(e.key==='Enter')submit(e.target.value);}); document.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',()=>submit(b.dataset.command)));
  $('#stop').addEventListener('click',stop); $('#speak').addEventListener('click',()=>{ if(!('SpeechRecognition' in window || 'webkitSpeechRecognition' in window)){setStatus('VOZ NO DISPONIBLE','Usá el comando escrito');say('El reconocimiento de voz no está disponible aquí. Usá el comando escrito.',false);return;} if(listening){stop();return;} const R=window.SpeechRecognition||window.webkitSpeechRecognition, r=new R(); r.lang='es-AR'; r.interimResults=false; r.onstart=()=>{listening=true;$('#voice-status').textContent='LISTENING';$('#waveform').classList.add('active');setStatus('ESCUCHANDO…','Hablá ahora');}; r.onerror=()=>{listening=false;setStatus('MICRÓFONO NO DISPONIBLE','Usá el comando escrito');$('#voice-status').textContent='VOICE READY';}; r.onend=()=>{listening=false;$('#waveform').classList.remove('active');}; r.onresult=e=>submit(e.results[0][0].transcript); r.start(); });
  $('#profile-button').addEventListener('click',()=>{$('#app').hidden=true;$('#onboarding').hidden=false;}); $('#personality').addEventListener('change',e=>{data.settings.personality=e.target.value;save();setStatus('CONFIGURACIÓN GUARDADA');}); $('#model').addEventListener('change',e=>{data.settings.model=e.target.value.trim()||'local-fallback';save();render();}); [['rate','rate-output','rate'],['pitch','pitch-output','pitch']].forEach(([id,out,name])=>$( '#'+id).addEventListener('input',e=>{data.settings[name]=Number(e.target.value);$('#'+out).textContent=Number(e.target.value).toFixed(2);save();}));
  $('#clear-history').addEventListener('click',()=>{data.history=[];save();render();setStatus('HISTORIAL LIMPIO');}); $('#clear-memory').addEventListener('click',()=>{if(confirm('¿Borrar la memoria de este perfil?')){data.memory=[];save();render();setStatus('MEMORIA BORRADA');}}); $('#reset').addEventListener('click',()=>{if(confirm('¿Reiniciar todos los datos de este perfil?')){localStorage.removeItem(key('data'));load();render();setStatus('PERFIL REINICIADO');}});
  $('#export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({app:'VANTA SYSTEM',profile,data,exported:new Date().toISOString()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`vanta-${profile.toLowerCase()}-backup.json`;a.click();URL.revokeObjectURL(a.href);setStatus('RESPALDO EXPORTADO');}); $('#import').addEventListener('click',()=>$('#file-input').click()); $('#file-input').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const incoming=JSON.parse(r.result);if(incoming.data){data={...data,...incoming.data};save();render();setStatus('RESPALDO IMPORTADO');}}catch{setStatus('IMPORTACIÓN RECHAZADA','Archivo JSON inválido');}};r.readAsText(f);});
  document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#command').focus();}}); setInterval(()=>{const d=new Date();$('#clock').textContent=d.toLocaleTimeString('es-AR');},1000);
})();
